name: quizzer
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  path: any
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^0.6.0
  file_picker: ^6.1.1
  undo: ^1.4.7
  flutter_reorderable_list: ^1.3.1
  sqflite: any
  path_provider: any
  shared_preferences: ^2.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Designer.png"
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/quizes_jsons/
